// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-ps.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader_RequestType int32

const (
	RequestHeader_NOT_USED   RequestHeader_RequestType = 0
	RequestHeader_PING       RequestHeader_RequestType = 256
	RequestHeader_RANGE_PULL RequestHeader_RequestType = 257
	RequestHeader_RANGE_PUSH RequestHeader_RequestType = 258
	RequestHeader_REPLICATE  RequestHeader_RequestType = 259
)

var RequestHeader_RequestType_name = map[int32]string{
	0:   "NOT_USED",
	256: "PING",
	257: "RANGE_PULL",
	258: "RANGE_PUSH",
	259: "REPLICATE",
}

var RequestHeader_RequestType_value = map[string]int32{
	"NOT_USED":   0,
	"PING":       256,
	"RANGE_PULL": 257,
	"RANGE_PUSH": 258,
	"REPLICATE":  259,
}

func (x RequestHeader_RequestType) String() string {
	return proto.EnumName(RequestHeader_RequestType_name, int32(x))
}

func (RequestHeader_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{3, 0}
}

type ResponseHeader_ResponseType int32

const (
	ResponseHeader_NOT_USED       ResponseHeader_ResponseType = 0
	ResponseHeader_ACK_PING       ResponseHeader_ResponseType = 512
	ResponseHeader_ACK_RANGE_PULL ResponseHeader_ResponseType = 513
	ResponseHeader_ACK_RANGE_PUSH ResponseHeader_ResponseType = 514
	ResponseHeader_ACK_REPLICATE  ResponseHeader_ResponseType = 515
)

var ResponseHeader_ResponseType_name = map[int32]string{
	0:   "NOT_USED",
	512: "ACK_PING",
	513: "ACK_RANGE_PULL",
	514: "ACK_RANGE_PUSH",
	515: "ACK_REPLICATE",
}

var ResponseHeader_ResponseType_value = map[string]int32{
	"NOT_USED":       0,
	"ACK_PING":       512,
	"ACK_RANGE_PULL": 513,
	"ACK_RANGE_PUSH": 514,
	"ACK_REPLICATE":  515,
}

func (x ResponseHeader_ResponseType) String() string {
	return proto.EnumName(ResponseHeader_ResponseType_name, int32(x))
}

func (ResponseHeader_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{4, 0}
}

type ResponseHeader_Status int32

const (
	ResponseHeader_OK    ResponseHeader_Status = 0
	ResponseHeader_ERROR ResponseHeader_Status = 1
)

var ResponseHeader_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var ResponseHeader_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x ResponseHeader_Status) String() string {
	return proto.EnumName(ResponseHeader_Status_name, int32(x))
}

func (ResponseHeader_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{4, 1}
}

type KV struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{0}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KV) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Range struct {
	Begin                uint64   `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{1}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetBegin() uint64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Range) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type RangeKV struct {
	Range                *Range   `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Kvs                  []*KV    `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeKV) Reset()         { *m = RangeKV{} }
func (m *RangeKV) String() string { return proto.CompactTextString(m) }
func (*RangeKV) ProtoMessage()    {}
func (*RangeKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{2}
}

func (m *RangeKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeKV.Unmarshal(m, b)
}
func (m *RangeKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeKV.Marshal(b, m, deterministic)
}
func (m *RangeKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeKV.Merge(m, src)
}
func (m *RangeKV) XXX_Size() int {
	return xxx_messageInfo_RangeKV.Size(m)
}
func (m *RangeKV) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeKV.DiscardUnknown(m)
}

var xxx_messageInfo_RangeKV proto.InternalMessageInfo

func (m *RangeKV) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *RangeKV) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type RequestHeader struct {
	SrcNodeRank          uint32                    `protobuf:"varint,1,opt,name=src_node_rank,json=srcNodeRank,proto3" json:"src_node_rank,omitempty"`
	DestNodeRank         uint32                    `protobuf:"varint,2,opt,name=dest_node_rank,json=destNodeRank,proto3" json:"dest_node_rank,omitempty"`
	Ts                   *timestamp.Timestamp      `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Type                 RequestHeader_RequestType `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.RequestHeader_RequestType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{3}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetSrcNodeRank() uint32 {
	if m != nil {
		return m.SrcNodeRank
	}
	return 0
}

func (m *RequestHeader) GetDestNodeRank() uint32 {
	if m != nil {
		return m.DestNodeRank
	}
	return 0
}

func (m *RequestHeader) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *RequestHeader) GetType() RequestHeader_RequestType {
	if m != nil {
		return m.Type
	}
	return RequestHeader_NOT_USED
}

type ResponseHeader struct {
	SrcNodeRank          uint32                      `protobuf:"varint,1,opt,name=src_node_rank,json=srcNodeRank,proto3" json:"src_node_rank,omitempty"`
	DestNodeRank         uint32                      `protobuf:"varint,2,opt,name=dest_node_rank,json=destNodeRank,proto3" json:"dest_node_rank,omitempty"`
	Ts                   *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Type                 ResponseHeader_ResponseType `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.ResponseHeader_ResponseType" json:"type,omitempty"`
	Status               ResponseHeader_Status       `protobuf:"varint,5,opt,name=status,proto3,enum=rpc.ResponseHeader_Status" json:"status,omitempty"`
	ErrorMsg             string                      `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{4}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSrcNodeRank() uint32 {
	if m != nil {
		return m.SrcNodeRank
	}
	return 0
}

func (m *ResponseHeader) GetDestNodeRank() uint32 {
	if m != nil {
		return m.DestNodeRank
	}
	return 0
}

func (m *ResponseHeader) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *ResponseHeader) GetType() ResponseHeader_ResponseType {
	if m != nil {
		return m.Type
	}
	return ResponseHeader_NOT_USED
}

func (m *ResponseHeader) GetStatus() ResponseHeader_Status {
	if m != nil {
		return m.Status
	}
	return ResponseHeader_OK
}

func (m *ResponseHeader) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type RangePullRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Range                *Range         `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RangePullRequest) Reset()         { *m = RangePullRequest{} }
func (m *RangePullRequest) String() string { return proto.CompactTextString(m) }
func (*RangePullRequest) ProtoMessage()    {}
func (*RangePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{5}
}

func (m *RangePullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePullRequest.Unmarshal(m, b)
}
func (m *RangePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePullRequest.Marshal(b, m, deterministic)
}
func (m *RangePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePullRequest.Merge(m, src)
}
func (m *RangePullRequest) XXX_Size() int {
	return xxx_messageInfo_RangePullRequest.Size(m)
}
func (m *RangePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangePullRequest proto.InternalMessageInfo

func (m *RangePullRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePullRequest) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

type RangePullResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV        `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RangePullResponse) Reset()         { *m = RangePullResponse{} }
func (m *RangePullResponse) String() string { return proto.CompactTextString(m) }
func (*RangePullResponse) ProtoMessage()    {}
func (*RangePullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{6}
}

func (m *RangePullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePullResponse.Unmarshal(m, b)
}
func (m *RangePullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePullResponse.Marshal(b, m, deterministic)
}
func (m *RangePullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePullResponse.Merge(m, src)
}
func (m *RangePullResponse) XXX_Size() int {
	return xxx_messageInfo_RangePullResponse.Size(m)
}
func (m *RangePullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RangePullResponse proto.InternalMessageInfo

func (m *RangePullResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePullResponse) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

type RangePushRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV       `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RangePushRequest) Reset()         { *m = RangePushRequest{} }
func (m *RangePushRequest) String() string { return proto.CompactTextString(m) }
func (*RangePushRequest) ProtoMessage()    {}
func (*RangePushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{7}
}

func (m *RangePushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePushRequest.Unmarshal(m, b)
}
func (m *RangePushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePushRequest.Marshal(b, m, deterministic)
}
func (m *RangePushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePushRequest.Merge(m, src)
}
func (m *RangePushRequest) XXX_Size() int {
	return xxx_messageInfo_RangePushRequest.Size(m)
}
func (m *RangePushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangePushRequest proto.InternalMessageInfo

func (m *RangePushRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePushRequest) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

type RangePushResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RangePushResponse) Reset()         { *m = RangePushResponse{} }
func (m *RangePushResponse) String() string { return proto.CompactTextString(m) }
func (*RangePushResponse) ProtoMessage()    {}
func (*RangePushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{8}
}

func (m *RangePushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePushResponse.Unmarshal(m, b)
}
func (m *RangePushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePushResponse.Marshal(b, m, deterministic)
}
func (m *RangePushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePushResponse.Merge(m, src)
}
func (m *RangePushResponse) XXX_Size() int {
	return xxx_messageInfo_RangePushResponse.Size(m)
}
func (m *RangePushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RangePushResponse proto.InternalMessageInfo

func (m *RangePushResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DuplicateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV       `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	DuplicateCounter     uint32         `protobuf:"varint,3,opt,name=duplicateCounter,proto3" json:"duplicateCounter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DuplicateRequest) Reset()         { *m = DuplicateRequest{} }
func (m *DuplicateRequest) String() string { return proto.CompactTextString(m) }
func (*DuplicateRequest) ProtoMessage()    {}
func (*DuplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{9}
}

func (m *DuplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateRequest.Unmarshal(m, b)
}
func (m *DuplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateRequest.Marshal(b, m, deterministic)
}
func (m *DuplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateRequest.Merge(m, src)
}
func (m *DuplicateRequest) XXX_Size() int {
	return xxx_messageInfo_DuplicateRequest.Size(m)
}
func (m *DuplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateRequest proto.InternalMessageInfo

func (m *DuplicateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DuplicateRequest) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

func (m *DuplicateRequest) GetDuplicateCounter() uint32 {
	if m != nil {
		return m.DuplicateCounter
	}
	return 0
}

type DuplicateResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DuplicateResponse) Reset()         { *m = DuplicateResponse{} }
func (m *DuplicateResponse) String() string { return proto.CompactTextString(m) }
func (*DuplicateResponse) ProtoMessage()    {}
func (*DuplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{10}
}

func (m *DuplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateResponse.Unmarshal(m, b)
}
func (m *DuplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateResponse.Marshal(b, m, deterministic)
}
func (m *DuplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateResponse.Merge(m, src)
}
func (m *DuplicateResponse) XXX_Size() int {
	return xxx_messageInfo_DuplicateResponse.Size(m)
}
func (m *DuplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateResponse proto.InternalMessageInfo

func (m *DuplicateResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.RequestHeader_RequestType", RequestHeader_RequestType_name, RequestHeader_RequestType_value)
	proto.RegisterEnum("rpc.ResponseHeader_ResponseType", ResponseHeader_ResponseType_name, ResponseHeader_ResponseType_value)
	proto.RegisterEnum("rpc.ResponseHeader_Status", ResponseHeader_Status_name, ResponseHeader_Status_value)
	proto.RegisterType((*KV)(nil), "rpc.KV")
	proto.RegisterType((*Range)(nil), "rpc.Range")
	proto.RegisterType((*RangeKV)(nil), "rpc.RangeKV")
	proto.RegisterType((*RequestHeader)(nil), "rpc.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "rpc.ResponseHeader")
	proto.RegisterType((*RangePullRequest)(nil), "rpc.RangePullRequest")
	proto.RegisterType((*RangePullResponse)(nil), "rpc.RangePullResponse")
	proto.RegisterType((*RangePushRequest)(nil), "rpc.RangePushRequest")
	proto.RegisterType((*RangePushResponse)(nil), "rpc.RangePushResponse")
	proto.RegisterType((*DuplicateRequest)(nil), "rpc.DuplicateRequest")
	proto.RegisterType((*DuplicateResponse)(nil), "rpc.DuplicateResponse")
}

func init() { proto.RegisterFile("go-ps.proto", fileDescriptor_bc169dcd4c07eef6) }

var fileDescriptor_bc169dcd4c07eef6 = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x5d, 0x6f, 0xda, 0x3c,
	0x18, 0x6d, 0x42, 0xa0, 0xf0, 0xf0, 0xf1, 0xe6, 0x75, 0xdf, 0x77, 0xca, 0xa8, 0xb4, 0x45, 0x56,
	0x2f, 0x50, 0xa7, 0x51, 0x29, 0xdb, 0xe5, 0x2e, 0x56, 0x51, 0xfa, 0x21, 0x3a, 0x8a, 0x0c, 0x65,
	0xbb, 0x63, 0x29, 0x71, 0x29, 0x82, 0xc6, 0x99, 0x6d, 0x90, 0x7a, 0xb7, 0x8f, 0x3f, 0x30, 0x69,
	0xda, 0x3f, 0xda, 0x0f, 0x9b, 0xe2, 0x84, 0x10, 0xa0, 0x93, 0xa6, 0x4a, 0xd3, 0xee, 0xfc, 0x1c,
	0x3f, 0xc7, 0xe7, 0x39, 0xc7, 0x4e, 0xa0, 0x38, 0x62, 0xcf, 0x03, 0x51, 0x0f, 0x38, 0x93, 0x0c,
	0x65, 0x78, 0x30, 0xac, 0x3e, 0x1d, 0x31, 0x36, 0x9a, 0xd2, 0x03, 0x05, 0x5d, 0xcd, 0xae, 0x0f,
	0xe4, 0xf8, 0x96, 0x0a, 0xe9, 0xde, 0x06, 0x51, 0x17, 0x3e, 0x06, 0xbd, 0xd5, 0x47, 0x26, 0x64,
	0x26, 0xf4, 0xce, 0xd2, 0x6c, 0xad, 0x66, 0x90, 0x70, 0x89, 0xfe, 0x83, 0xec, 0xdc, 0x9d, 0xce,
	0xa8, 0xa5, 0xdb, 0x5a, 0xad, 0x44, 0xa2, 0x02, 0x59, 0xb0, 0x3d, 0xa7, 0x5c, 0x8c, 0x99, 0x6f,
	0x65, 0x6c, 0xad, 0x56, 0x26, 0x8b, 0x12, 0x1f, 0x40, 0x96, 0xb8, 0xfe, 0x88, 0x86, 0xc4, 0x2b,
	0x3a, 0x1a, 0xfb, 0xf1, 0x61, 0x51, 0x11, 0x0a, 0x50, 0xdf, 0x53, 0x87, 0x19, 0x24, 0x5c, 0xe2,
	0x63, 0xd8, 0x56, 0x84, 0x56, 0x1f, 0xd9, 0x90, 0xe5, 0xe1, 0x52, 0x51, 0x8a, 0x0e, 0xd4, 0x79,
	0x30, 0xac, 0xab, 0x4d, 0x12, 0x6d, 0xa0, 0xc7, 0x90, 0x99, 0xcc, 0x85, 0xa5, 0xdb, 0x99, 0x5a,
	0xd1, 0xd9, 0x56, 0xfb, 0xad, 0x3e, 0x09, 0x31, 0xfc, 0x4d, 0x87, 0x32, 0xa1, 0x1f, 0x66, 0x54,
	0xc8, 0x53, 0xea, 0x7a, 0x94, 0x23, 0x0c, 0x65, 0xc1, 0x87, 0x03, 0x9f, 0x79, 0x74, 0xc0, 0x5d,
	0x7f, 0xa2, 0x8e, 0x2d, 0x93, 0xa2, 0xe0, 0xc3, 0x36, 0xf3, 0x28, 0x71, 0xfd, 0x09, 0xda, 0x83,
	0x8a, 0x47, 0x85, 0x4c, 0x35, 0xe9, 0xaa, 0xa9, 0x14, 0xa2, 0x49, 0xd7, 0x3e, 0xe8, 0x52, 0x28,
	0xa7, 0x45, 0xa7, 0x5a, 0x8f, 0xa2, 0xac, 0x2f, 0xa2, 0xac, 0xf7, 0x16, 0x51, 0x12, 0x5d, 0x0a,
	0xe4, 0x80, 0x21, 0xef, 0x02, 0x6a, 0x19, 0xb6, 0x56, 0xab, 0x38, 0x4f, 0x22, 0x0f, 0xe9, 0xb9,
	0x16, 0x55, 0xef, 0x2e, 0xa0, 0x44, 0xf5, 0xe2, 0x77, 0x50, 0x4c, 0x81, 0xa8, 0x04, 0xf9, 0xf6,
	0x45, 0x6f, 0x70, 0xd9, 0x6d, 0x1e, 0x99, 0x5b, 0xa8, 0x00, 0x46, 0xe7, 0xac, 0x7d, 0x62, 0x7e,
	0xd4, 0xd1, 0x3f, 0x00, 0xe4, 0xb0, 0x7d, 0xd2, 0x1c, 0x74, 0x2e, 0xcf, 0xcf, 0xcd, 0x4f, 0x2b,
	0x40, 0xf7, 0xd4, 0xfc, 0xac, 0xa3, 0x0a, 0x14, 0x48, 0xb3, 0x73, 0x7e, 0xd6, 0x38, 0xec, 0x35,
	0xcd, 0x2f, 0x3a, 0xfe, 0x9e, 0x81, 0x0a, 0xa1, 0x22, 0x60, 0xbe, 0xa0, 0x7f, 0x35, 0x96, 0x97,
	0x2b, 0xb1, 0xd8, 0x71, 0x2c, 0xe9, 0xc1, 0x92, 0x72, 0x19, 0x0c, 0x72, 0x20, 0x27, 0xa4, 0x2b,
	0x67, 0xc2, 0xca, 0x2a, 0x5e, 0xf5, 0x3e, 0x5e, 0x57, 0x75, 0x90, 0xb8, 0x13, 0xed, 0x42, 0x81,
	0x72, 0xce, 0xf8, 0xe0, 0x56, 0x8c, 0xac, 0x9c, 0xad, 0xd5, 0x0a, 0x24, 0xaf, 0x80, 0x37, 0x62,
	0x84, 0xc7, 0x50, 0x4a, 0xcb, 0xac, 0x45, 0x5d, 0x86, 0xfc, 0x61, 0xa3, 0x35, 0x88, 0xe2, 0x36,
	0xd0, 0x0e, 0x54, 0xc2, 0x32, 0x1d, 0xf9, 0x06, 0x18, 0xc6, 0x6e, 0x20, 0x04, 0x65, 0x05, 0x2e,
	0xa3, 0x37, 0xf0, 0x2e, 0xe4, 0xa2, 0xc9, 0x50, 0x0e, 0xf4, 0x8b, 0x96, 0xba, 0xc9, 0x6c, 0x93,
	0x90, 0x0b, 0x62, 0x6a, 0xf8, 0x3d, 0x98, 0xea, 0x61, 0x77, 0x66, 0xd3, 0x69, 0x7c, 0xf5, 0x68,
	0x1f, 0x72, 0x37, 0xca, 0x51, 0xfc, 0xfe, 0xd1, 0xe6, 0xdb, 0x21, 0x71, 0xc7, 0xf2, 0x53, 0xd1,
	0x7f, 0xf1, 0xa9, 0xe0, 0x6b, 0xf8, 0x37, 0xa5, 0x10, 0x59, 0x46, 0xcf, 0xd6, 0x24, 0x76, 0xee,
	0xc9, 0x33, 0xd1, 0xd8, 0x83, 0xdc, 0x64, 0x7e, 0xe4, 0x4a, 0x37, 0x16, 0x29, 0x2d, 0x45, 0x5a,
	0x7d, 0x12, 0xef, 0x61, 0x2f, 0x71, 0x22, 0x6e, 0x1e, 0xe2, 0xe4, 0xf7, 0x54, 0x5e, 0x27, 0x6e,
	0x42, 0x95, 0x07, 0xb8, 0xc1, 0x5f, 0x35, 0x30, 0x8f, 0x66, 0xc1, 0x74, 0x3c, 0x74, 0x25, 0xfd,
	0x63, 0x83, 0xa2, 0x7d, 0x30, 0xbd, 0x85, 0x4a, 0x83, 0xcd, 0x7c, 0x49, 0x79, 0xfc, 0x8b, 0xdc,
	0xc0, 0x43, 0x53, 0xa9, 0x89, 0x1e, 0x60, 0xca, 0xf9, 0xa1, 0x41, 0xbe, 0x23, 0xba, 0x94, 0xcf,
	0x29, 0x47, 0xaf, 0xa0, 0x90, 0xdc, 0x38, 0xfa, 0x7f, 0x39, 0x5d, 0xea, 0x8d, 0x55, 0x1f, 0xad,
	0xc3, 0xd1, 0xb1, 0x78, 0x2b, 0xc5, 0x16, 0x37, 0xab, 0xec, 0xe4, 0x5e, 0x57, 0xd9, 0xcb, 0x8b,
	0x88, 0xd8, 0x89, 0x95, 0x98, 0xbd, 0x1e, 0x76, 0xcc, 0xde, 0x70, 0x8c, 0xb7, 0x1c, 0x08, 0x5d,
	0xbc, 0x65, 0x7c, 0x42, 0xb9, 0x53, 0x86, 0x62, 0x83, 0x31, 0xee, 0x8d, 0x7d, 0x57, 0x32, 0x7e,
	0x95, 0x53, 0xff, 0x93, 0x17, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xd8, 0xe9, 0xc2, 0xd3,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PsServerClient is the client API for PsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PsServerClient interface {
	RangePull(ctx context.Context, in *RangePullRequest, opts ...grpc.CallOption) (*RangePullResponse, error)
	RangePush(ctx context.Context, in *RangePushRequest, opts ...grpc.CallOption) (*RangePushResponse, error)
	Duplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*DuplicateResponse, error)
}

type psServerClient struct {
	cc *grpc.ClientConn
}

func NewPsServerClient(cc *grpc.ClientConn) PsServerClient {
	return &psServerClient{cc}
}

func (c *psServerClient) RangePull(ctx context.Context, in *RangePullRequest, opts ...grpc.CallOption) (*RangePullResponse, error) {
	out := new(RangePullResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/RangePull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psServerClient) RangePush(ctx context.Context, in *RangePushRequest, opts ...grpc.CallOption) (*RangePushResponse, error) {
	out := new(RangePushResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/RangePush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psServerClient) Duplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*DuplicateResponse, error) {
	out := new(DuplicateResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/Duplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PsServerServer is the server API for PsServer service.
type PsServerServer interface {
	RangePull(context.Context, *RangePullRequest) (*RangePullResponse, error)
	RangePush(context.Context, *RangePushRequest) (*RangePushResponse, error)
	Duplicate(context.Context, *DuplicateRequest) (*DuplicateResponse, error)
}

// UnimplementedPsServerServer can be embedded to have forward compatible implementations.
type UnimplementedPsServerServer struct {
}

func (*UnimplementedPsServerServer) RangePull(ctx context.Context, req *RangePullRequest) (*RangePullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangePull not implemented")
}
func (*UnimplementedPsServerServer) RangePush(ctx context.Context, req *RangePushRequest) (*RangePushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangePush not implemented")
}
func (*UnimplementedPsServerServer) Duplicate(ctx context.Context, req *DuplicateRequest) (*DuplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Duplicate not implemented")
}

func RegisterPsServerServer(s *grpc.Server, srv PsServerServer) {
	s.RegisterService(&_PsServer_serviceDesc, srv)
}

func _PsServer_RangePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).RangePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/RangePull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).RangePull(ctx, req.(*RangePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsServer_RangePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).RangePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/RangePush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).RangePush(ctx, req.(*RangePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsServer_Duplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).Duplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/Duplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).Duplicate(ctx, req.(*DuplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PsServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PsServer",
	HandlerType: (*PsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RangePull",
			Handler:    _PsServer_RangePull_Handler,
		},
		{
			MethodName: "RangePush",
			Handler:    _PsServer_RangePush_Handler,
		},
		{
			MethodName: "Duplicate",
			Handler:    _PsServer_Duplicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-ps.proto",
}

// PsWorkerClient is the client API for PsWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PsWorkerClient interface {
}

type psWorkerClient struct {
	cc *grpc.ClientConn
}

func NewPsWorkerClient(cc *grpc.ClientConn) PsWorkerClient {
	return &psWorkerClient{cc}
}

// PsWorkerServer is the server API for PsWorker service.
type PsWorkerServer interface {
}

// UnimplementedPsWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedPsWorkerServer struct {
}

func RegisterPsWorkerServer(s *grpc.Server, srv PsWorkerServer) {
	s.RegisterService(&_PsWorker_serviceDesc, srv)
}

var _PsWorker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PsWorker",
	HandlerType: (*PsWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "go-ps.proto",
}

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "go-ps.proto",
}
