// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-ps.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_NOT_USED    Role = 0
	Role_SERVER_NODE Role = 1
	Role_WORKER_NODE Role = 2
)

var Role_name = map[int32]string{
	0: "NOT_USED",
	1: "SERVER_NODE",
	2: "WORKER_NODE",
}

var Role_value = map[string]int32{
	"NOT_USED":    0,
	"SERVER_NODE": 1,
	"WORKER_NODE": 2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{0}
}

type RequestHeader_RequestType int32

const (
	RequestHeader_NOT_USED   RequestHeader_RequestType = 0
	RequestHeader_HEARTBEAT  RequestHeader_RequestType = 256
	RequestHeader_RANGE_PULL RequestHeader_RequestType = 257
	RequestHeader_RANGE_PUSH RequestHeader_RequestType = 258
	RequestHeader_REPLICATE  RequestHeader_RequestType = 259
	RequestHeader_REGISTER   RequestHeader_RequestType = 260
	RequestHeader_UNREGISTER RequestHeader_RequestType = 261
	RequestHeader_PULL_NODES RequestHeader_RequestType = 262
)

var RequestHeader_RequestType_name = map[int32]string{
	0:   "NOT_USED",
	256: "HEARTBEAT",
	257: "RANGE_PULL",
	258: "RANGE_PUSH",
	259: "REPLICATE",
	260: "REGISTER",
	261: "UNREGISTER",
	262: "PULL_NODES",
}

var RequestHeader_RequestType_value = map[string]int32{
	"NOT_USED":   0,
	"HEARTBEAT":  256,
	"RANGE_PULL": 257,
	"RANGE_PUSH": 258,
	"REPLICATE":  259,
	"REGISTER":   260,
	"UNREGISTER": 261,
	"PULL_NODES": 262,
}

func (x RequestHeader_RequestType) String() string {
	return proto.EnumName(RequestHeader_RequestType_name, int32(x))
}

func (RequestHeader_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{4, 0}
}

type ResponseHeader_ResponseType int32

const (
	ResponseHeader_NOT_USED       ResponseHeader_ResponseType = 0
	ResponseHeader_ACK_RANGE_PULL ResponseHeader_ResponseType = 513
	ResponseHeader_ACK_RANGE_PUSH ResponseHeader_ResponseType = 514
	ResponseHeader_ACK_REPLICATE  ResponseHeader_ResponseType = 515
	ResponseHeader_ACK_REGISTER   ResponseHeader_ResponseType = 516
	ResponseHeader_ACK_UNREGISTER ResponseHeader_ResponseType = 517
	ResponseHeader_ACK_PULL_NODES ResponseHeader_ResponseType = 518
)

var ResponseHeader_ResponseType_name = map[int32]string{
	0:   "NOT_USED",
	513: "ACK_RANGE_PULL",
	514: "ACK_RANGE_PUSH",
	515: "ACK_REPLICATE",
	516: "ACK_REGISTER",
	517: "ACK_UNREGISTER",
	518: "ACK_PULL_NODES",
}

var ResponseHeader_ResponseType_value = map[string]int32{
	"NOT_USED":       0,
	"ACK_RANGE_PULL": 513,
	"ACK_RANGE_PUSH": 514,
	"ACK_REPLICATE":  515,
	"ACK_REGISTER":   516,
	"ACK_UNREGISTER": 517,
	"ACK_PULL_NODES": 518,
}

func (x ResponseHeader_ResponseType) String() string {
	return proto.EnumName(ResponseHeader_ResponseType_name, int32(x))
}

func (ResponseHeader_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{5, 0}
}

type ResponseHeader_Status int32

const (
	ResponseHeader_OK    ResponseHeader_Status = 0
	ResponseHeader_ERROR ResponseHeader_Status = 1
)

var ResponseHeader_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var ResponseHeader_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x ResponseHeader_Status) String() string {
	return proto.EnumName(ResponseHeader_Status_name, int32(x))
}

func (ResponseHeader_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{5, 1}
}

type KV struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{0}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KV) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Range struct {
	Begin                uint64   `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{1}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetBegin() uint64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Range) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type RangeKV struct {
	Range                *Range   `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Kvs                  []*KV    `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeKV) Reset()         { *m = RangeKV{} }
func (m *RangeKV) String() string { return proto.CompactTextString(m) }
func (*RangeKV) ProtoMessage()    {}
func (*RangeKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{2}
}

func (m *RangeKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeKV.Unmarshal(m, b)
}
func (m *RangeKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeKV.Marshal(b, m, deterministic)
}
func (m *RangeKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeKV.Merge(m, src)
}
func (m *RangeKV) XXX_Size() int {
	return xxx_messageInfo_RangeKV.Size(m)
}
func (m *RangeKV) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeKV.DiscardUnknown(m)
}

var xxx_messageInfo_RangeKV proto.InternalMessageInfo

func (m *RangeKV) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *RangeKV) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type Node struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Rank                 uint32   `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Role                 Role     `protobuf:"varint,3,opt,name=role,proto3,enum=rpc.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{3}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Node) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NOT_USED
}

type RequestHeader struct {
	SrcNodeRank          uint32                    `protobuf:"varint,1,opt,name=src_node_rank,json=srcNodeRank,proto3" json:"src_node_rank,omitempty"`
	DestNodeRank         uint32                    `protobuf:"varint,2,opt,name=dest_node_rank,json=destNodeRank,proto3" json:"dest_node_rank,omitempty"`
	Ts                   *timestamp.Timestamp      `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Type                 RequestHeader_RequestType `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.RequestHeader_RequestType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{4}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetSrcNodeRank() uint32 {
	if m != nil {
		return m.SrcNodeRank
	}
	return 0
}

func (m *RequestHeader) GetDestNodeRank() uint32 {
	if m != nil {
		return m.DestNodeRank
	}
	return 0
}

func (m *RequestHeader) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *RequestHeader) GetType() RequestHeader_RequestType {
	if m != nil {
		return m.Type
	}
	return RequestHeader_NOT_USED
}

type ResponseHeader struct {
	SrcNodeRank          uint32                      `protobuf:"varint,1,opt,name=src_node_rank,json=srcNodeRank,proto3" json:"src_node_rank,omitempty"`
	DestNodeRank         uint32                      `protobuf:"varint,2,opt,name=dest_node_rank,json=destNodeRank,proto3" json:"dest_node_rank,omitempty"`
	Ts                   *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Type                 ResponseHeader_ResponseType `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.ResponseHeader_ResponseType" json:"type,omitempty"`
	Status               ResponseHeader_Status       `protobuf:"varint,5,opt,name=status,proto3,enum=rpc.ResponseHeader_Status" json:"status,omitempty"`
	ErrorMsg             string                      `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{5}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSrcNodeRank() uint32 {
	if m != nil {
		return m.SrcNodeRank
	}
	return 0
}

func (m *ResponseHeader) GetDestNodeRank() uint32 {
	if m != nil {
		return m.DestNodeRank
	}
	return 0
}

func (m *ResponseHeader) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *ResponseHeader) GetType() ResponseHeader_ResponseType {
	if m != nil {
		return m.Type
	}
	return ResponseHeader_NOT_USED
}

func (m *ResponseHeader) GetStatus() ResponseHeader_Status {
	if m != nil {
		return m.Status
	}
	return ResponseHeader_OK
}

func (m *ResponseHeader) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type RangePullRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Range                *Range         `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RangePullRequest) Reset()         { *m = RangePullRequest{} }
func (m *RangePullRequest) String() string { return proto.CompactTextString(m) }
func (*RangePullRequest) ProtoMessage()    {}
func (*RangePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{6}
}

func (m *RangePullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePullRequest.Unmarshal(m, b)
}
func (m *RangePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePullRequest.Marshal(b, m, deterministic)
}
func (m *RangePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePullRequest.Merge(m, src)
}
func (m *RangePullRequest) XXX_Size() int {
	return xxx_messageInfo_RangePullRequest.Size(m)
}
func (m *RangePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangePullRequest proto.InternalMessageInfo

func (m *RangePullRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePullRequest) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

type RangePullResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV        `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RangePullResponse) Reset()         { *m = RangePullResponse{} }
func (m *RangePullResponse) String() string { return proto.CompactTextString(m) }
func (*RangePullResponse) ProtoMessage()    {}
func (*RangePullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{7}
}

func (m *RangePullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePullResponse.Unmarshal(m, b)
}
func (m *RangePullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePullResponse.Marshal(b, m, deterministic)
}
func (m *RangePullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePullResponse.Merge(m, src)
}
func (m *RangePullResponse) XXX_Size() int {
	return xxx_messageInfo_RangePullResponse.Size(m)
}
func (m *RangePullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RangePullResponse proto.InternalMessageInfo

func (m *RangePullResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePullResponse) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

type RangePushRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV       `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RangePushRequest) Reset()         { *m = RangePushRequest{} }
func (m *RangePushRequest) String() string { return proto.CompactTextString(m) }
func (*RangePushRequest) ProtoMessage()    {}
func (*RangePushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{8}
}

func (m *RangePushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePushRequest.Unmarshal(m, b)
}
func (m *RangePushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePushRequest.Marshal(b, m, deterministic)
}
func (m *RangePushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePushRequest.Merge(m, src)
}
func (m *RangePushRequest) XXX_Size() int {
	return xxx_messageInfo_RangePushRequest.Size(m)
}
func (m *RangePushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangePushRequest proto.InternalMessageInfo

func (m *RangePushRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangePushRequest) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

type RangePushResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RangePushResponse) Reset()         { *m = RangePushResponse{} }
func (m *RangePushResponse) String() string { return proto.CompactTextString(m) }
func (*RangePushResponse) ProtoMessage()    {}
func (*RangePushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{9}
}

func (m *RangePushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangePushResponse.Unmarshal(m, b)
}
func (m *RangePushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangePushResponse.Marshal(b, m, deterministic)
}
func (m *RangePushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangePushResponse.Merge(m, src)
}
func (m *RangePushResponse) XXX_Size() int {
	return xxx_messageInfo_RangePushResponse.Size(m)
}
func (m *RangePushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RangePushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RangePushResponse proto.InternalMessageInfo

func (m *RangePushResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DuplicateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KvData               *RangeKV       `protobuf:"bytes,2,opt,name=kvData,proto3" json:"kvData,omitempty"`
	DuplicateCounter     uint32         `protobuf:"varint,3,opt,name=duplicateCounter,proto3" json:"duplicateCounter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DuplicateRequest) Reset()         { *m = DuplicateRequest{} }
func (m *DuplicateRequest) String() string { return proto.CompactTextString(m) }
func (*DuplicateRequest) ProtoMessage()    {}
func (*DuplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{10}
}

func (m *DuplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateRequest.Unmarshal(m, b)
}
func (m *DuplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateRequest.Marshal(b, m, deterministic)
}
func (m *DuplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateRequest.Merge(m, src)
}
func (m *DuplicateRequest) XXX_Size() int {
	return xxx_messageInfo_DuplicateRequest.Size(m)
}
func (m *DuplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateRequest proto.InternalMessageInfo

func (m *DuplicateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DuplicateRequest) GetKvData() *RangeKV {
	if m != nil {
		return m.KvData
	}
	return nil
}

func (m *DuplicateRequest) GetDuplicateCounter() uint32 {
	if m != nil {
		return m.DuplicateCounter
	}
	return 0
}

type DuplicateResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DuplicateResponse) Reset()         { *m = DuplicateResponse{} }
func (m *DuplicateResponse) String() string { return proto.CompactTextString(m) }
func (*DuplicateResponse) ProtoMessage()    {}
func (*DuplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{11}
}

func (m *DuplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateResponse.Unmarshal(m, b)
}
func (m *DuplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateResponse.Marshal(b, m, deterministic)
}
func (m *DuplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateResponse.Merge(m, src)
}
func (m *DuplicateResponse) XXX_Size() int {
	return xxx_messageInfo_DuplicateResponse.Size(m)
}
func (m *DuplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateResponse proto.InternalMessageInfo

func (m *DuplicateResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type HeartbeatRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{12}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type HeartbeatResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{13}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type RegisterRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Ip                   string         `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Role                 Role           `protobuf:"varint,3,opt,name=role,proto3,enum=rpc.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{14}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RegisterRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RegisterRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NOT_USED
}

type RegisterResponse struct {
	Header                  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Rank                    uint32          `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	ReplicateFactor         uint32          `protobuf:"varint,3,opt,name=replicate_factor,json=replicateFactor,proto3" json:"replicate_factor,omitempty"`
	ReplicateAfterAggregate bool            `protobuf:"varint,4,opt,name=replicate_after_aggregate,json=replicateAfterAggregate,proto3" json:"replicate_after_aggregate,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}        `json:"-"`
	XXX_unrecognized        []byte          `json:"-"`
	XXX_sizecache           int32           `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{15}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RegisterResponse) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RegisterResponse) GetReplicateFactor() uint32 {
	if m != nil {
		return m.ReplicateFactor
	}
	return 0
}

func (m *RegisterResponse) GetReplicateAfterAggregate() bool {
	if m != nil {
		return m.ReplicateAfterAggregate
	}
	return false
}

type UnregisterRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Ip                   string         `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Rank                 uint32         `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UnregisterRequest) Reset()         { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()    {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{16}
}

func (m *UnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRequest.Unmarshal(m, b)
}
func (m *UnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRequest.Merge(m, src)
}
func (m *UnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterRequest.Size(m)
}
func (m *UnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRequest proto.InternalMessageInfo

func (m *UnregisterRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UnregisterRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UnregisterRequest) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type UnregisterResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UnregisterResponse) Reset()         { *m = UnregisterResponse{} }
func (m *UnregisterResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterResponse) ProtoMessage()    {}
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{17}
}

func (m *UnregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterResponse.Unmarshal(m, b)
}
func (m *UnregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterResponse.Merge(m, src)
}
func (m *UnregisterResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterResponse.Size(m)
}
func (m *UnregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterResponse proto.InternalMessageInfo

func (m *UnregisterResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PullNodesRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PullNodesRequest) Reset()         { *m = PullNodesRequest{} }
func (m *PullNodesRequest) String() string { return proto.CompactTextString(m) }
func (*PullNodesRequest) ProtoMessage()    {}
func (*PullNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{18}
}

func (m *PullNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNodesRequest.Unmarshal(m, b)
}
func (m *PullNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNodesRequest.Marshal(b, m, deterministic)
}
func (m *PullNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNodesRequest.Merge(m, src)
}
func (m *PullNodesRequest) XXX_Size() int {
	return xxx_messageInfo_PullNodesRequest.Size(m)
}
func (m *PullNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullNodesRequest proto.InternalMessageInfo

func (m *PullNodesRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PullNodesResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nodes                []*Node         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PullNodesResponse) Reset()         { *m = PullNodesResponse{} }
func (m *PullNodesResponse) String() string { return proto.CompactTextString(m) }
func (*PullNodesResponse) ProtoMessage()    {}
func (*PullNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc169dcd4c07eef6, []int{19}
}

func (m *PullNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNodesResponse.Unmarshal(m, b)
}
func (m *PullNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNodesResponse.Marshal(b, m, deterministic)
}
func (m *PullNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNodesResponse.Merge(m, src)
}
func (m *PullNodesResponse) XXX_Size() int {
	return xxx_messageInfo_PullNodesResponse.Size(m)
}
func (m *PullNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullNodesResponse proto.InternalMessageInfo

func (m *PullNodesResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PullNodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.Role", Role_name, Role_value)
	proto.RegisterEnum("rpc.RequestHeader_RequestType", RequestHeader_RequestType_name, RequestHeader_RequestType_value)
	proto.RegisterEnum("rpc.ResponseHeader_ResponseType", ResponseHeader_ResponseType_name, ResponseHeader_ResponseType_value)
	proto.RegisterEnum("rpc.ResponseHeader_Status", ResponseHeader_Status_name, ResponseHeader_Status_value)
	proto.RegisterType((*KV)(nil), "rpc.KV")
	proto.RegisterType((*Range)(nil), "rpc.Range")
	proto.RegisterType((*RangeKV)(nil), "rpc.RangeKV")
	proto.RegisterType((*Node)(nil), "rpc.Node")
	proto.RegisterType((*RequestHeader)(nil), "rpc.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "rpc.ResponseHeader")
	proto.RegisterType((*RangePullRequest)(nil), "rpc.RangePullRequest")
	proto.RegisterType((*RangePullResponse)(nil), "rpc.RangePullResponse")
	proto.RegisterType((*RangePushRequest)(nil), "rpc.RangePushRequest")
	proto.RegisterType((*RangePushResponse)(nil), "rpc.RangePushResponse")
	proto.RegisterType((*DuplicateRequest)(nil), "rpc.DuplicateRequest")
	proto.RegisterType((*DuplicateResponse)(nil), "rpc.DuplicateResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "rpc.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "rpc.HeartbeatResponse")
	proto.RegisterType((*RegisterRequest)(nil), "rpc.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "rpc.RegisterResponse")
	proto.RegisterType((*UnregisterRequest)(nil), "rpc.UnregisterRequest")
	proto.RegisterType((*UnregisterResponse)(nil), "rpc.UnregisterResponse")
	proto.RegisterType((*PullNodesRequest)(nil), "rpc.PullNodesRequest")
	proto.RegisterType((*PullNodesResponse)(nil), "rpc.PullNodesResponse")
}

func init() { proto.RegisterFile("go-ps.proto", fileDescriptor_bc169dcd4c07eef6) }

var fileDescriptor_bc169dcd4c07eef6 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xae, 0xd7, 0xae, 0xfd, 0xfc, 0x91, 0xcd, 0xb4, 0xa5, 0xae, 0x2b, 0xa8, 0x35, 0xea,
	0x21, 0x04, 0xe1, 0x48, 0x06, 0x21, 0x81, 0x2a, 0xc0, 0x24, 0x9b, 0x26, 0x72, 0x88, 0xa3, 0xb1,
	0xe3, 0x1e, 0xcd, 0xc6, 0x9e, 0x6c, 0x2c, 0x3b, 0xbb, 0xcb, 0xcc, 0xd8, 0x52, 0x6e, 0x7c, 0x95,
	0x23, 0xe2, 0xc6, 0xff, 0xc2, 0xb9, 0x27, 0xfe, 0x2a, 0x34, 0xb3, 0x9f, 0xb6, 0x83, 0x40, 0x2b,
	0x10, 0xb7, 0x9d, 0xdf, 0xbc, 0xf7, 0x7e, 0xef, 0x7b, 0x16, 0x2a, 0x8e, 0xf7, 0xa1, 0xcf, 0xdb,
	0x3e, 0xf3, 0x84, 0x87, 0xf2, 0xcc, 0x9f, 0x34, 0x9f, 0x3b, 0x9e, 0xe7, 0x2c, 0xe8, 0x81, 0x82,
	0xae, 0x96, 0xd7, 0x07, 0x62, 0x76, 0x4b, 0xb9, 0xb0, 0x6f, 0xfd, 0x40, 0x0a, 0x1f, 0x83, 0xde,
	0x1b, 0x21, 0x13, 0xf2, 0x73, 0x7a, 0xd7, 0xd0, 0x5a, 0xda, 0x9e, 0x41, 0xe4, 0x27, 0x7a, 0x04,
	0x85, 0x95, 0xbd, 0x58, 0xd2, 0x86, 0xde, 0xd2, 0xf6, 0xaa, 0x24, 0x38, 0xa0, 0x06, 0x3c, 0x58,
	0x51, 0xc6, 0x67, 0x9e, 0xdb, 0xc8, 0xb7, 0xb4, 0xbd, 0x1a, 0x89, 0x8e, 0xf8, 0x00, 0x0a, 0xc4,
	0x76, 0x1d, 0x2a, 0x15, 0xaf, 0xa8, 0x33, 0x73, 0x43, 0x63, 0xc1, 0x41, 0x12, 0x50, 0x77, 0xaa,
	0x8c, 0x19, 0x44, 0x7e, 0xe2, 0x63, 0x78, 0xa0, 0x14, 0x7a, 0x23, 0xd4, 0x82, 0x02, 0x93, 0x9f,
	0x4a, 0xa5, 0xd2, 0x81, 0x36, 0xf3, 0x27, 0x6d, 0x75, 0x49, 0x82, 0x0b, 0xf4, 0x14, 0xf2, 0xf3,
	0x15, 0x6f, 0xe8, 0xad, 0xfc, 0x5e, 0xa5, 0xf3, 0x40, 0xdd, 0xf7, 0x46, 0x44, 0x62, 0xf8, 0x14,
	0x8c, 0x73, 0x6f, 0x4a, 0x51, 0x1d, 0xf4, 0x99, 0xaf, 0x2c, 0x94, 0x89, 0x3e, 0xf3, 0x11, 0x02,
	0x83, 0xd9, 0xee, 0x5c, 0x51, 0xd6, 0x88, 0xfa, 0x46, 0xef, 0x82, 0xc1, 0xbc, 0x05, 0x55, 0xbe,
	0xd7, 0x3b, 0xe5, 0x80, 0xc7, 0x5b, 0x50, 0xa2, 0x60, 0xfc, 0x87, 0x0e, 0x35, 0x42, 0xbf, 0x5d,
	0x52, 0x2e, 0x4e, 0xa8, 0x3d, 0xa5, 0x0c, 0x61, 0xa8, 0x71, 0x36, 0x19, 0xbb, 0xde, 0x94, 0x8e,
	0x95, 0x35, 0x4d, 0x59, 0xab, 0x70, 0x36, 0x91, 0xa4, 0x44, 0x1a, 0x7d, 0x01, 0xf5, 0x29, 0xe5,
	0x22, 0x25, 0x14, 0x50, 0x56, 0x25, 0x1a, 0x4b, 0xed, 0x83, 0x2e, 0xb8, 0x22, 0xae, 0x74, 0x9a,
	0xed, 0xa0, 0x2a, 0xed, 0xa8, 0x2a, 0xed, 0x61, 0x54, 0x15, 0xa2, 0x0b, 0x8e, 0x3a, 0x60, 0x88,
	0x3b, 0x9f, 0x36, 0x0c, 0xe5, 0xe6, 0x7b, 0x81, 0x9b, 0x69, 0xbf, 0xa2, 0xd3, 0xf0, 0xce, 0xa7,
	0x44, 0xc9, 0xe2, 0x5f, 0x34, 0xa8, 0xa4, 0x50, 0x54, 0x85, 0xd2, 0x79, 0x7f, 0x38, 0xbe, 0x1c,
	0x58, 0x47, 0x66, 0x0e, 0xd5, 0xa1, 0x7c, 0x62, 0x75, 0xc9, 0xf0, 0x2b, 0xab, 0x3b, 0x34, 0xbf,
	0xd3, 0xd1, 0x0e, 0x00, 0xe9, 0x9e, 0xbf, 0xb2, 0xc6, 0x17, 0x97, 0x67, 0x67, 0xe6, 0xf7, 0x6b,
	0xc0, 0xe0, 0xc4, 0xfc, 0x41, 0x97, 0x1a, 0xc4, 0xba, 0x38, 0x3b, 0x3d, 0xec, 0x0e, 0x2d, 0xf3,
	0x47, 0x1d, 0xd5, 0xa0, 0x44, 0xac, 0x57, 0xa7, 0x83, 0xa1, 0x45, 0xcc, 0x9f, 0x94, 0xfc, 0xe5,
	0x79, 0x0c, 0xbc, 0x51, 0x80, 0xb4, 0x35, 0x3e, 0xef, 0x1f, 0x59, 0x03, 0xf3, 0x67, 0x1d, 0xbf,
	0xcd, 0x43, 0x9d, 0x50, 0xee, 0x7b, 0x2e, 0xa7, 0xff, 0x6b, 0x36, 0x3f, 0x5e, 0xcb, 0x66, 0x2b,
	0xcc, 0x66, 0xda, 0xb1, 0xf8, 0x98, 0xe4, 0x13, 0x75, 0xa0, 0xc8, 0x85, 0x2d, 0x96, 0xbc, 0x51,
	0x50, 0x7a, 0xcd, 0xfb, 0xf4, 0x06, 0x4a, 0x82, 0x84, 0x92, 0xe8, 0x19, 0x94, 0x29, 0x63, 0x1e,
	0x1b, 0xdf, 0x72, 0xa7, 0x51, 0x54, 0x9d, 0x58, 0x52, 0xc0, 0xd7, 0xdc, 0xc1, 0xbf, 0x69, 0x50,
	0x4d, 0xf3, 0x6c, 0x54, 0xe8, 0x21, 0xd4, 0xbb, 0x87, 0xbd, 0x71, 0xba, 0x2a, 0xc6, 0x26, 0x28,
	0x2b, 0x63, 0x20, 0x04, 0x35, 0x05, 0x26, 0xd5, 0x31, 0xd0, 0x2e, 0x54, 0x03, 0x2c, 0xaa, 0x50,
	0xac, 0x9b, 0xae, 0x52, 0x0c, 0xa6, 0x2b, 0x65, 0xe0, 0x67, 0x50, 0x0c, 0x02, 0x41, 0x45, 0xd0,
	0xfb, 0x3d, 0x33, 0x87, 0xca, 0x50, 0xb0, 0x08, 0xe9, 0x13, 0x53, 0xc3, 0xdf, 0x80, 0xa9, 0x26,
	0xf1, 0x62, 0xb9, 0x58, 0x84, 0xfd, 0x85, 0xf6, 0xa1, 0x78, 0xa3, 0x12, 0x10, 0x0e, 0x2c, 0xda,
	0xee, 0x50, 0x12, 0x4a, 0x24, 0xb3, 0xad, 0xff, 0xc5, 0x6c, 0xe3, 0x6b, 0xd8, 0x4d, 0x31, 0x04,
	0x09, 0x42, 0x1f, 0x6c, 0x50, 0x3c, 0xbc, 0x27, 0xfd, 0x31, 0xc7, 0x0b, 0x28, 0xce, 0x57, 0x47,
	0xb6, 0xb0, 0x43, 0x92, 0x6a, 0x42, 0xd2, 0x1b, 0x91, 0xf0, 0x0e, 0x4f, 0xe3, 0x48, 0xf8, 0x4d,
	0x96, 0x48, 0xfe, 0x19, 0xcb, 0x97, 0x71, 0x34, 0x92, 0x25, 0x43, 0x34, 0xf8, 0x57, 0x0d, 0xcc,
	0xa3, 0xa5, 0xbf, 0x98, 0x4d, 0x6c, 0x41, 0xff, 0x33, 0x47, 0xd1, 0x3e, 0x98, 0xd3, 0x88, 0xe5,
	0xd0, 0x5b, 0xba, 0x82, 0xb2, 0x70, 0xa7, 0x6f, 0xe1, 0x32, 0xa8, 0x94, 0x47, 0x59, 0x82, 0xfa,
	0x1c, 0xcc, 0x13, 0x6a, 0x33, 0x71, 0x45, 0x6d, 0x91, 0x21, 0x26, 0xe9, 0x41, 0x4a, 0x3f, 0x8b,
	0x07, 0x0b, 0xd8, 0x21, 0xd4, 0x99, 0x71, 0x41, 0x59, 0x96, 0xa4, 0x06, 0xcf, 0x8b, 0x1e, 0x3f,
	0x2f, 0x7f, 0xf3, 0x94, 0xfc, 0xae, 0x81, 0x99, 0xd0, 0x65, 0x69, 0xea, 0xfb, 0xde, 0xaf, 0xf7,
	0xc1, 0x64, 0x34, 0xac, 0xc3, 0xf8, 0xda, 0x9e, 0x08, 0x2f, 0xaa, 0xd9, 0x4e, 0x8c, 0x1f, 0x2b,
	0x18, 0x7d, 0x06, 0x4f, 0x13, 0x51, 0xfb, 0x5a, 0x50, 0x36, 0xb6, 0x1d, 0x87, 0x51, 0xc7, 0x16,
	0xc1, 0x2a, 0x2c, 0x91, 0x27, 0xb1, 0x40, 0x57, 0xde, 0x77, 0xa3, 0x6b, 0x3c, 0x81, 0xdd, 0x4b,
	0x97, 0xfd, 0x8b, 0xc9, 0x8a, 0x62, 0xc9, 0x27, 0xb1, 0xe0, 0x2e, 0xa0, 0x34, 0x49, 0xc6, 0xa6,
	0x92, 0x4b, 0x43, 0xbe, 0x0a, 0x3c, 0x4b, 0x53, 0xd9, 0xb0, 0x9b, 0xd2, 0xcf, 0x52, 0xa4, 0xe7,
	0x50, 0x90, 0x0f, 0x55, 0xf4, 0x67, 0x12, 0xb4, 0x81, 0x7a, 0xa5, 0x02, 0x7c, 0xff, 0x13, 0x30,
	0x64, 0x57, 0x6c, 0x2c, 0xfb, 0x1d, 0xa8, 0x0c, 0x2c, 0x32, 0xb2, 0x88, 0x5a, 0xc2, 0xa6, 0x26,
	0x81, 0xd7, 0x7d, 0xd2, 0x8b, 0x00, 0xbd, 0xf3, 0x56, 0x83, 0xd2, 0x05, 0x1f, 0x50, 0xb6, 0xa2,
	0x0c, 0xbd, 0x84, 0x72, 0xbc, 0x21, 0xd1, 0xe3, 0x64, 0x9a, 0x53, 0x3b, 0xb9, 0xf9, 0xce, 0x26,
	0x1c, 0xf8, 0x8b, 0x73, 0x29, 0x6d, 0x7e, 0xb3, 0xae, 0x1d, 0xef, 0xc1, 0x75, 0xed, 0x64, 0x71,
	0x05, 0xda, 0xf1, 0xe8, 0x87, 0xda, 0x9b, 0xcb, 0x29, 0xd4, 0xde, 0xda, 0x10, 0x38, 0xd7, 0x01,
	0x19, 0xc5, 0x6b, 0x8f, 0xcd, 0x29, 0xeb, 0xbc, 0xd1, 0xa1, 0x72, 0xe8, 0x79, 0x6c, 0x3a, 0x73,
	0x6d, 0xd9, 0xa1, 0x2f, 0xa1, 0x1c, 0x8f, 0x74, 0x68, 0x79, 0x73, 0x45, 0x84, 0x96, 0xb7, 0x26,
	0x1f, 0xe7, 0xd0, 0xa7, 0x50, 0x8a, 0xe6, 0x0b, 0x3d, 0x0a, 0x4b, 0xb4, 0xd6, 0xb0, 0xcd, 0xc7,
	0x1b, 0x68, 0xac, 0xfa, 0x05, 0x40, 0xd2, 0x79, 0x28, 0xa0, 0xd8, 0xea, 0xf7, 0xe6, 0x93, 0x2d,
	0x3c, 0x9d, 0x93, 0xb8, 0x6f, 0x42, 0xcf, 0x37, 0xfb, 0x30, 0xf4, 0x7c, 0xab, 0xbd, 0x70, 0xee,
	0xaa, 0xa8, 0xfe, 0x53, 0x3e, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff, 0x05, 0xd9, 0x8d, 0x34, 0xad,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PsServerClient is the client API for PsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PsServerClient interface {
	RangePull(ctx context.Context, in *RangePullRequest, opts ...grpc.CallOption) (*RangePullResponse, error)
	RangePush(ctx context.Context, in *RangePushRequest, opts ...grpc.CallOption) (*RangePushResponse, error)
	Duplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*DuplicateResponse, error)
}

type psServerClient struct {
	cc *grpc.ClientConn
}

func NewPsServerClient(cc *grpc.ClientConn) PsServerClient {
	return &psServerClient{cc}
}

func (c *psServerClient) RangePull(ctx context.Context, in *RangePullRequest, opts ...grpc.CallOption) (*RangePullResponse, error) {
	out := new(RangePullResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/RangePull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psServerClient) RangePush(ctx context.Context, in *RangePushRequest, opts ...grpc.CallOption) (*RangePushResponse, error) {
	out := new(RangePushResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/RangePush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psServerClient) Duplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*DuplicateResponse, error) {
	out := new(DuplicateResponse)
	err := c.cc.Invoke(ctx, "/rpc.PsServer/Duplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PsServerServer is the server API for PsServer service.
type PsServerServer interface {
	RangePull(context.Context, *RangePullRequest) (*RangePullResponse, error)
	RangePush(context.Context, *RangePushRequest) (*RangePushResponse, error)
	Duplicate(context.Context, *DuplicateRequest) (*DuplicateResponse, error)
}

// UnimplementedPsServerServer can be embedded to have forward compatible implementations.
type UnimplementedPsServerServer struct {
}

func (*UnimplementedPsServerServer) RangePull(ctx context.Context, req *RangePullRequest) (*RangePullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangePull not implemented")
}
func (*UnimplementedPsServerServer) RangePush(ctx context.Context, req *RangePushRequest) (*RangePushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangePush not implemented")
}
func (*UnimplementedPsServerServer) Duplicate(ctx context.Context, req *DuplicateRequest) (*DuplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Duplicate not implemented")
}

func RegisterPsServerServer(s *grpc.Server, srv PsServerServer) {
	s.RegisterService(&_PsServer_serviceDesc, srv)
}

func _PsServer_RangePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).RangePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/RangePull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).RangePull(ctx, req.(*RangePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsServer_RangePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).RangePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/RangePush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).RangePush(ctx, req.(*RangePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsServer_Duplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsServerServer).Duplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.PsServer/Duplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsServerServer).Duplicate(ctx, req.(*DuplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PsServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PsServer",
	HandlerType: (*PsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RangePull",
			Handler:    _PsServer_RangePull_Handler,
		},
		{
			MethodName: "RangePush",
			Handler:    _PsServer_RangePush_Handler,
		},
		{
			MethodName: "Duplicate",
			Handler:    _PsServer_Duplicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-ps.proto",
}

// PsWorkerClient is the client API for PsWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PsWorkerClient interface {
}

type psWorkerClient struct {
	cc *grpc.ClientConn
}

func NewPsWorkerClient(cc *grpc.ClientConn) PsWorkerClient {
	return &psWorkerClient{cc}
}

// PsWorkerServer is the server API for PsWorker service.
type PsWorkerServer interface {
}

// UnimplementedPsWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedPsWorkerServer struct {
}

func RegisterPsWorkerServer(s *grpc.Server, srv PsWorkerServer) {
	s.RegisterService(&_PsWorker_serviceDesc, srv)
}

var _PsWorker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PsWorker",
	HandlerType: (*PsWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "go-ps.proto",
}

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
	PullNodes(ctx context.Context, in *PullNodesRequest, opts ...grpc.CallOption) (*PullNodesResponse, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/rpc.Coordinator/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/rpc.Coordinator/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, "/rpc.Coordinator/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PullNodes(ctx context.Context, in *PullNodesRequest, opts ...grpc.CallOption) (*PullNodesResponse, error) {
	out := new(PullNodesResponse)
	err := c.cc.Invoke(ctx, "/rpc.Coordinator/PullNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	PullNodes(context.Context, *PullNodesRequest) (*PullNodesResponse, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (*UnimplementedCoordinatorServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedCoordinatorServer) Unregister(ctx context.Context, req *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (*UnimplementedCoordinatorServer) PullNodes(ctx context.Context, req *PullNodesRequest) (*PullNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullNodes not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Coordinator/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Coordinator/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Coordinator/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PullNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PullNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Coordinator/PullNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PullNodes(ctx, req.(*PullNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Coordinator_Heartbeat_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Coordinator_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Coordinator_Unregister_Handler,
		},
		{
			MethodName: "PullNodes",
			Handler:    _Coordinator_PullNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-ps.proto",
}
